baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TzuHan Blog'
theme = 'PaperMod'
[params]
  ShowFullTextinHome = false # Ensure this is false
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  [params.homeInfoParams]
    Title = "Welcome to My Blog "
    Content = "Sharing insights about AI, machine learning, and more!"
  [params.assets]
    favicon = "favicon.ico"
    favicon16x16 = "images/favicon-16x16.png"
    favicon32x32 = "images/favicon-32x32.png"
    apple_touch_icon = "images/apple-touch-icon.png"
    safari_pinned_tab = "images/safari-pinned-tab.svg"
  [params.cover]
    enabled = true
    linkFullImages = true
    hiddenInList = false
    hiddenInSingle = false
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3