baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TzuHan Blog'
theme = 'PaperMod'
[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  [params.homeInfoParams]
    enable = false # Set to false if you want a consistent layout