baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'TzuHan Blog'
theme = 'PaperMod'
[params]
  ShowFullTextinHome = false
  ShowFeaturedPosts = true
  ShowReadingTime = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowWordCount = true
  ShowToc = true
  TocOpen = false
  [params.homeInfoParams]
    enable = false
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "All Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3